@api = http://localhost:3001/api/v1

###

GET {{api}}/users

###

POST {{api}}/users/register
Content-Type: application/json

{
  "username": "test2",
  "email": "test2",
  "password": "test2"
}

###

POST {{api}}/users/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

GET {{api}}/events

###

POST {{api}}/events
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjc2MDQ3NDIxLCJleHAiOjE2NzYwNTEwMjF9.3zMYxcYzIU5445WkBxnC9zA2qySjuihezv-LPTSOFcc

{
  "name": "test3",
  "event_date": "2023-02-10"
}

###

POST {{api}}/users/join-event
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc2MDQ4NTAzLCJleHAiOjE2NzYwNTIxMDN9.S3R5zb8L4TNHN18SMO520qh235Ceyl--WBKaM2aD1Ug

{
  "event_id": 3
}
